# Создание базы данных

In [1]:
import sqlite3
import random 

conn = sqlite3.connect('metro.db')
conn.execute('PRAGMA foreign_keys = ON')

In [2]:
c = conn.cursor()
#create TicketType
conn.execute('''CREATE TABLE TicketType
             (Name Varchar(100) PRIMARY KEY, 
             Priveleges Varchar(100) NOT NULL, 
             PeriodofValidity INTERGER)''')
#create Manager
conn.execute('''CREATE TABLE Manager
             (ManagerID Varchar(100) PRIMARY KEY, 
             Surname Varchar(100) NOT NULL, 
             Name Varchar(100) NOT NULL, 
             Patronymic Varchar(100))''')
#create Cashier
conn.execute('''CREATE TABLE Cashier
             (CashierID Varchar(100) PRIMARY KEY, 
             Surname Varchar(100) NOT NULL, 
             Name Varchar(100) NOT NULL, 
             Patronymic Varchar(100), 
             Experience INTEGER NOT NULL,
             ManagerID Varchar(100) , 
             FOREIGN KEY(ManagerID) REFERENCES Manager(ManagerID) \
             ON UPDATE CASCADE)''')
#create Route
conn.execute('''CREATE TABLE Route
            (RouteID Varchar(100) PRIMARY KEY)''')
#create Station
conn.execute('''CREATE TABLE Station (
            StationID Varchar(100) PRIMARY KEY,
            StationName Varchar(100) NOT NULL)''')
#create Train
conn.execute('''CREATE TABLE Train (TrainID Varchar(100) PRIMARY KEY,
            SessionBegining Varchar(100) NOT NULL,
            SessionEnd Varchar(100) NOT NULL,
            RouteID Varchar(100) ,
            FOREIGN KEY(RouteID) REFERENCES Route(RouteID) ON UPDATE \
            CASCADE ON DELETE CASCADE)''')
#create Passenger
conn.execute('''CREATE TABLE Passenger
             (PassengerID Varchar(100) PRIMARY KEY, 
             Surname Varchar(100) NOT NULL, 
             Name Varchar(100) NOT NULL, 
             Patronymic Varchar(100), 
             TrainID Varchar(100), 
             FOREIGN KEY(TrainID) REFERENCES Train(TrainID) ON \
             DELETE SET NULL)''')
#create Drivers
conn.execute('''CREATE TABLE Driver (DriverID text PRIMARY KEY,
            Surname Varchar(100) NOT NULL,
            Name Varchar(100) NOT NULL,
            Patronymic Varchar(100),
            Experience INTEGER NOT NULL,
            SessionBegining Varchar(100) NOT NULL,
            SessionEnd Varchar(100) NOT NULL,
            TrainID Varchar(100) ,
            ManagerID Varchar(100),
            FOREIGN KEY(TrainID) REFERENCES Train(TrainID) ON \
            UPDATE CASCADE ON DELETE CASCADE, 
            FOREIGN KEY(ManagerID) REFERENCES Manager(ManagerID) ON \
            UPDATE CASCADE)''')
#create RouteToStation
conn.execute('''CREATE TABLE RouteToStation
             (ID Varchar(100) PRIMARY KEY, 
             OrderNumber INTEGER NOT NULL,
             RouteID Varchar(100),
             StationID Varchar(100) ,
             FOREIGN KEY(RouteID) REFERENCES Route(RouteID) ON \
             UPDATE CASCADE ON DELETE CASCADE,
             FOREIGN KEY(StationID) REFERENCES Station(StationID) ON \
             UPDATE CASCADE ON DELETE CASCADE)''')
#create StationToStation
conn.execute('''CREATE TABLE StationToStation
             (ID Varchar(100) PRIMARY KEY,
             FirstStation Varchar(100) ,
             SecondStation Varchar(100) ,
             FOREIGN KEY(FirstStation) REFERENCES Station(StationID) ON \
             UPDATE CASCADE ON DELETE CASCADE,
             FOREIGN KEY(SecondStation) REFERENCES Station(StationID) ON \
             UPDATE CASCADE ON DELETE CASCADE)''')
#create TicketMachine
conn.execute('''CREATE TABLE TicketMachine
             (MachineID Varchar(100) PRIMARY KEY, 
             StationID Varchar(100),
             FOREIGN KEY(StationID) REFERENCES Station(StationID) ON \
             UPDATE CASCADE ON DELETE CASCADE)''')
#create Ticket
conn.execute('''CREATE TABLE Ticket
             (TicketID Varchar(100) PRIMARY KEY, 
             NumberOfTrips INTEGER, 
             TypeOfTicket Varchar(100) ,
             PassengerID Varchar(100),
             StationID Varchar(100),
             CashierID Varchar(100),
             MachineID Varchar(100),
             FOREIGN KEY(TypeOfTicket) REFERENCES TicketType(Name) ON \
             UPDATE CASCADE ON DELETE CASCADE,
             FOREIGN KEY(PassengerID) REFERENCES Passenger(PassengerID) ON \
             DELETE SET NULL,
             FOREIGN KEY(StationID) REFERENCES Station(StationID) ON \
             DELETE SET NULL,
             FOREIGN KEY(CashierID) REFERENCES Cashier(CashierID) ON \
             DELETE SET NULL,
             FOREIGN KEY(MachineID) REFERENCES TicketMachine(MachineID) ON \
             DELETE SET NULL)''')

In [3]:
#insert TicketType
ticket_types = ['advance', 'offpeak', 'anytime', 'season']
c.execute("INSERT INTO TicketType VALUES ('advance','only \
        valid on the date specified', '1')")
c.execute("INSERT INTO TicketType VALUES ('offpeak','buy any time, \
        travel off-peak', '30')")
c.execute("INSERT INTO TicketType VALUES ('anytime','buy any time, \
            travel any time', '30')")
c.execute("INSERT INTO TicketType VALUES ('season','travel between \
        two stations', '30')")

#insert Manager
female_surnames = [u'Ковалева', u'Власова', u'Рогозина', 
                   u'Краснова', u'Лаврова', u'Светлова',
                   u'Теплова', u'Баталина', u'Соболева', 
                   u'Морозова', u'Громова', u'Александрова']
female_names = [u'Анастасия', u'Александра', u'Ангелина', 
                u'Татьяна', u'Дарья', u'Виктория', 
                u'Елена', u'Елизавета', u'Надежда', 
                u'Кристина', u'Светлана', u'Нина']
female_patronymics = [u'Артуровна', u'Александровна', u'Дмитриевна',
                      u'Федоровна', u'Робертовна', u'Эдуардовна', 
                      u'Игоревна', u'Сергеевна', u'Андреевна']
male_surnames = [u'Соболев', u'Морозов', u'Громов', u'Алмазов', 
                 u'Державин', u'Богатырев', u'Майоров', 
                 u'Адмиралов', u'Любимов', u'Воронцов',
                 u'Рогозин', u'Никитин', u'Ленин']
male_names = [u'Артём', u'Александр', u'Максим', u'Иван', 
              u'Михаил', u'Данила', u'Дмитрий', u'Андрей', 
              u'Кирилл', u'Никита', u'Сергей', u'Роберт',
              u'Игорь', u'Павел']
male_patronymics = [u'Артурович', u'Александрович', 
                    u'Дмитриевич', u'Федорович', u'Робертович', 
                    u'Эдуардович', u'Иванович', u'Сергеевич', 
                    u'Андреевич', u'Игоревич']
digits = [str(i) for i in range(10)]

manager_number = 5
manager_id_length = 2
manager_ids = []
for i in range(manager_number):
    manager_id = i
    manager_ids.append(manager_id)
    if random.randint(1, 2) == 1:
        surname = random.choice(female_surnames)
        name = random.choice(female_names)
        patronymic = random.choice(female_patronymics)
    else:
        surname = random.choice(male_surnames)
        name = random.choice(male_names)
        patronymic = random.choice(male_patronymics)
    c.execute(u"INSERT INTO Manager \
                VALUES (\'{}\',\'{}\', \'{}\', \'{}\')" \
              .format(manager_id, surname, name, patronymic))

#insert Cashier
cashier_number = 20
cashier_id_length = 3
cashier_ids = []
for i in range(cashier_number):
    cashier_id = i
    cashier_ids.append(cashier_id)
    if random.randint(1, 2) == 1:
        surname = random.choice(female_surnames)
        name = random.choice(female_names)
        patronymic = random.choice(female_patronymics)
    else:
        surname = random.choice(male_surnames)
        name = random.choice(male_names)
        patronymic = random.choice(male_patronymics)
    experience = random.randint(1, 30)
    manager_id = random.choice(manager_ids)
    c.execute(u"INSERT INTO Cashier VALUES \
        (\'{}\',\'{}\', \'{}\', \'{}\', \'{}\', \'{}\')" \
        .format(cashier_id, surname, name,\
                patronymic, experience, manager_id))

# insert Route
route_number = 10
route_id_length = 16
route_ids = []
for i in range(route_number):
    route_id = i
    route_ids.append(route_id)
    c.execute("INSERT INTO Route \
        VALUES (\'{}\')".format(route_id))

#insert Station
station_names = []
with open('metro_ru.txt', 'r') as f:
    for line in f:
        station = line.strip('\n')
        station_names.append(station.strip())
station_id_length = 16
station_ids = []
for index, station in enumerate(station_names):
    station_ids.append(index + 1)
    c.execute(u"INSERT INTO Station VALUES \
        (\'{}\', \'{}\')".format(index + 1, station))

#insert Train
train_number = 20
train_id_length = 16
train_ids = []
for i in range(train_number):
    train_id = i
    train_ids.append(train_id)
    start_hour = random.randint(6, 20)
    start_minute = random.randint(1, 59)
    start_second = random.randint(1, 59)
    end_hour = random.randint(start_hour + 1, 23)
    end_minute = random.randint(1, 59)
    end_second = random.randint(1, 59)
    route_id = random.choice(route_ids)
    c.execute("INSERT INTO Train VALUES (\'" + \
              str(train_id) + "\', \
              \'" + "%02d:%02d:%02d" % \
                (start_hour, start_minute, start_second) + \
              "\', \'" + "%02d:%02d:%02d" % (end_hour,\
                end_minute, end_second) + "\', \
              \'" + str(route_id) + "\')")

#insert Passenger
passenger_number = 200
passenger_id_length = 10
passenger_ids = []
for i in range(passenger_number):
    passenger_id = i
    passenger_ids.append(passenger_id)
    train_id = random.choice(train_ids)
    if random.randint(1, 2) == 1:
        surname = random.choice(female_surnames)
        name = random.choice(female_names)
        patronymic = random.choice(female_patronymics)
    else:
        surname = random.choice(male_surnames)
        name = random.choice(male_names)
        patronymic = random.choice(male_patronymics)
    c.execute(u"INSERT INTO Passenger VALUES \
        (\'{}\',\'{}\', \'{}\', \'{}\', \'{}\')" \
        .format(passenger_id, surname, \
                name, patronymic, train_id))
    
#insert Drivers
driver_number = 15
driver_id_length = 10
driver_ids = []
for i in range(driver_number):
    driver_id = i
    driver_ids.append(driver_id)
    experience = random.randint(1, 30)
    train_id = random.choice(train_ids)
    manager_id = random.choice(manager_ids)
    start_hour = random.randint(6, 20)
    start_minute = random.randint(1, 59)
    start_second = random.randint(1, 59)
    start_time = "%02d:%02d:%02d" % (start_hour, \
                    start_minute, start_second)
    end_hour = random.randint(start_hour + 1, 23)
    end_minute = random.randint(1, 59)
    end_second = random.randint(1, 59)
    end_time = "%02d:%02d:%02d" % (end_hour, \
        end_minute, end_second)
    if random.randint(1, 2) == 1:
        surname = random.choice(female_surnames)
        name = random.choice(female_names)
        patronymic = random.choice(female_patronymics)
    else:
        surname = random.choice(male_surnames)
        name = random.choice(male_names)
        patronymic = random.choice(male_patronymics)
    c.execute(u"INSERT INTO Driver VALUES \
    (\'{}\',\'{}\', \'{}\', \'{}\', \'{}\', \
        \'{}\', \'{}\', \'{}\', \'{}\')" \
            .format(driver_id, surname, name,\
                patronymic, experience,\
                start_time, end_time, \
                train_id, manager_id))

#insert TicketMachine
machine_number = 5
machine_id_length = 8
machine_ids = []
for i in range(machine_number):
    machine_id = i
    machine_ids.append(machine_id)
    station_id = random.choice(station_ids)
    c.execute(u"INSERT INTO TicketMachine VALUES \
            (\'{}\', \'{}\')" \
            .format(machine_id, station_id))

#insert Ticket
ticket_number = 800
ticket_id_length = 8
for _ in range(ticket_number):
    ticket_id = ''.join([random.choice(digits) \
        for i in range(ticket_id_length)])
    number_of_trips = random.randint(1, 20)
    type_of_ticket = random.choice(ticket_types)
    passenger_id = random.choice(passenger_ids)
    station_id = random.choice(station_ids)
    if random.randint(1, 2) == 1:
        cashier_id = random.choice(cashier_ids)
        c.execute(u"INSERT INTO Ticket VALUES \
        (\'{}\',\'{}\',\'{}\',\'{}\',\'{}\',\'{}\',{})" \
        .format(ticket_id, number_of_trips,\
                type_of_ticket, passenger_id,\
                station_id, cashier_id, 'NULL'))
    else:
        machine_id = random.choice(machine_ids)
        c.execute(u"INSERT INTO Ticket VALUES \
        (\'{}\',\'{}\',\'{}\',\'{}\',\'{}\',{},\'{}\')" \
              .format(ticket_id, number_of_trips, \
                type_of_ticket, passenger_id,\
                    station_id, 'NULL', machine_id))

#create RouteToStation
current_index = 0
for i in range(route_number):
    route_length = random.randint(2, 15)
    stations = set()
    for order_number in range(route_length):
        while True:
            station_id = random.choice(station_ids)
            if not station_id in stations:
                stations.add(station_id)
                break
        c.execute(u"INSERT INTO RouteToStation VALUES\
            (\'{}\',\'{}\',\'{}\',\'{}\')" \
            .format(current_index, order_number, i, station_id))
        current_index += 1
              
#insert StationToStation
station_relationships = 10
for i in range(station_relationships):
    first_id = random.choice(station_ids)
    second_id = random.choice(station_ids)
    c.execute(u"INSERT INTO StationToStation VALUES \
        (\'{}\',\'{}\',\'{}\')" \
        .format(i, first_id, second_id))

In [4]:
conn.commit()

In [5]:
conn.close()

#### Посмотрим на какие-нибудь данные:

In [6]:
conn = sqlite3.connect('metro.db')
c = conn.cursor()
for row in c.execute('SELECT * FROM Manager'):
    print (row[1])

Громова
Ковалева
Морозов
Богатырев
Богатырев

# Приложение

In [7]:
#-*- coding: utf-8 -*-
conn = sqlite3.connect('metro.db')
c = conn.cursor()

print("This application is made to help interact with database Metro")

def prints():
    print("\nHere you can find the set of requests available now \n")
    print("get( entity ) - shows the table of entity\n")
    print("RouteByNumber( numberOfRoute ) - returns the ordered set of \
          stations in given route\n")
    print("NumberOfTicketsAtStation( nameOfStation ) - returns the number \
          of tickets bought at given station\n")
    print("MaxStationByNumberOfTickets() - returns the stations, where the \
          maximum number of tickets were bought\n")
    print("NumberOfPassengersAtRoute( numberOfRoute )- returns the number \
          of passengers who went by given route\n")
    print("ManagerWithMaximumNumberOfSubordinates() - returns the managers \
        with maximum number of subordinates\n")
    print("StationsWhereMostOfTicketsWereBoughtFromMachines() - returns the \
        stations where the maximum number of tickets were bought from Machines\n")
    print("quitApp() - if you want to quit this application")

prints()


#0
#0
def get(entity):
    conn.row_factory = sqlite3.Row
    cursor = conn.execute('select * from ' + entity)
    print (' | '.join(cursor.fetchone().keys()))
    for row in c.execute('SELECT * FROM ' + entity):
        print (row[0], row[1], row[2], row[3])
    prints()

def quitApp():
    quit()


#1
def RouteByNumber(numberOfRoute):
    string = "select StationName \
    from RouteToStation as r, Station as s \
    where r.StationID = s.StationID \
    and r.RouteID = '" + str(numberOfRoute) + \
    "'order by OrderNumber"
    for row in c.execute(string):
            if len(row) != 0:
                print(row[0])
            else:
                print("Error")
    prints()
    

#2
def NumberOfTicketsAtStation(nameOfStation):
    string = "select count(*) from Ticket as t, Station as s \
    where (t.StationID = s.StationID) and \
    (s.StationName = '" + nameOfStation + "')"

    for row in c.execute(string):
            print (row[0])
    prints()

    
#3
def MaxStationByNumberOfTickets():
    string = "select st.StationName from Station st \
        where (select count(*) from Ticket t \
        where (t.StationID=st.StationID)) = \
        (select max(BoughtTicket) \
        from (select (select count(*) from Ticket t \
        where t.StationID = s.StationID) as BoughtTicket \
        from Station s))"
    for row in c.execute(string):
        print(row[0])
    prints()
    
    
#4
def NumberOfPassengersAtRoute(numberOfRoute):
    string = 'Select count(*) from Passenger p, Train t \
        where (p.TrainID=t.TrainID and t.RouteID='
    string = string + "'" + str(numberOfRoute) + "')"
    for row in c.execute(string):
        if len(row) != 0:
            print(row[0])
        else:
            print("Error")
    prints()

    
#5
def ManagerWithMaximumNumberOfSubordinates():
    string = "select Surname, Name, \
        Patronymic from Manager mng\
        where (select count(*) from Cashier c \
        where c.ManagerID = mng.ManagerID) +\
        (select count(*) from Driver d \
        where d.ManagerID = mng.ManagerID) =\
        (select max(NumberOfSubordinates)\
        from\
        (\
        select\
        ((select count(*) from Cashier c\
        where (c.ManagerID = m.ManagerID)) +\
        (select count(*) from Driver d\
        where (d.ManagerID = m.ManagerID))\
        ) as NumberOfSubordinates\
        from Manager m\
        )\
        )"
    for row in c.execute(string):
        print (row[0], row[1], row[2])
    prints()


#6
def StationsWhereMostOfTicketsWereBoughtFromMachines():
    string = "Select s.StationName from Station s \
        where (select count(*) from Ticket t \
        where (t.StationId = s.StationId) \
        and (t.CashierID is NULL)) > \
        (select count(*) from Ticket t \
        where (t.StationId = s.StationId) \
        and (t.MachineID is NULL))"

    for row in c.execute(string):
        print(row[0])
    prints()

This application is made to help interact with database Metro

Here you can find the set of requests available now

get( entity ) - shows the table of entity

RouteByNumber( numberOfRoute ) - returns the ordered set of           stations in given route

NumberOfTicketsAtStation( nameOfStation ) - returns the number           of tickets bought at given station

MaxStationByNumberOfTickets() - returns the stations, where the           maximum number of tickets were bought

NumberOfPassengersAtRoute( numberOfRoute )- returns the number           of passengers who went by given route

ManagerWithMaximumNumberOfSubordinates() - returns the managers         with maximum number of subordinates

StationsWhereMostOfTicketsWereBoughtFromMachines() - returns the         stations where the maximum number of tickets were bought from Machines

quitApp() - if you want to quit this application

### Примеры использования:

In [8]:
get('Train')

TrainID | SessionBegining | SessionEnd | RouteID
0 14:01:15 17:58:43 8
1 07:22:27 23:35:39 2
2 18:40:01 20:46:44 2
3 13:38:43 19:09:54 1
4 17:46:29 18:39:27 7
5 07:26:40 14:07:15 8
6 19:19:26 22:24:42 8
7 17:11:26 20:49:50 3
8 10:31:58 19:39:06 6
9 07:34:16 18:34:19 6
10 07:30:54 22:04:06 1
11 09:50:07 14:41:04 0
12 08:21:53 16:06:54 1
13 09:57:28 12:42:38 3
14 08:19:53 18:50:30 5
15 15:40:03 17:36:27 0
16 15:57:32 16:13:21 5
17 18:09:04 20:17:58 1
18 19:15:40 21:05:08 0
19 16:24:03 21:59:54 3

Here you can find the set of requests available now

get( entity ) - shows the table of entity

RouteByNumber( numberOfRoute ) - returns the ordered set of           stations in given route

NumberOfTicketsAtStation( nameOfStation ) - returns the number           of tickets bought at given station

MaxStationByNumberOfTickets() - returns the stations, where the           maximum number of tickets were bought

NumberOfPassengersAtRoute( numberOfRoute )- returns the number           of passengers who went by given route

ManagerWithMaximumNumberOfSubordinates() - returns the managers         with maximum number of subordinates

StationsWhereMostOfTicketsWereBoughtFromMachines() - returns the         stations where the maximum number of tickets were bought from Machines

quitApp() - if you want to quit this application

In [9]:
RouteByNumber(5)

Беговая
Октябрьское поле
Кузьминки
Улица Скобелевская
Улица Старокачаловская
Лубянка
Щёлковская
Курская

Here you can find the set of requests available now

get( entity ) - shows the table of entity

RouteByNumber( numberOfRoute ) - returns the ordered set of           stations in given route

NumberOfTicketsAtStation( nameOfStation ) - returns the number           of tickets bought at given station

MaxStationByNumberOfTickets() - returns the stations, where the           maximum number of tickets were bought

NumberOfPassengersAtRoute( numberOfRoute )- returns the number           of passengers who went by given route

ManagerWithMaximumNumberOfSubordinates() - returns the managers         with maximum number of subordinates

StationsWhereMostOfTicketsWereBoughtFromMachines() - returns the         stations where the maximum number of tickets were bought from Machines

quitApp() - if you want to quit this application

In [10]:
NumberOfTicketsAtStation('Аэропорт')

3

Here you can find the set of requests available now

get( entity ) - shows the table of entity

RouteByNumber( numberOfRoute ) - returns the ordered set of           stations in given route

NumberOfTicketsAtStation( nameOfStation ) - returns the number           of tickets bought at given station

MaxStationByNumberOfTickets() - returns the stations, where the           maximum number of tickets were bought

NumberOfPassengersAtRoute( numberOfRoute )- returns the number           of passengers who went by given route

ManagerWithMaximumNumberOfSubordinates() - returns the managers         with maximum number of subordinates

StationsWhereMostOfTicketsWereBoughtFromMachines() - returns the         stations where the maximum number of tickets were bought from Machines

quitApp() - if you want to quit this application

In [11]:
MaxStationByNumberOfTickets()

Красные ворота

Here you can find the set of requests available now

get( entity ) - shows the table of entity

RouteByNumber( numberOfRoute ) - returns the ordered set of           stations in given route

NumberOfTicketsAtStation( nameOfStation ) - returns the number           of tickets bought at given station

MaxStationByNumberOfTickets() - returns the stations, where the           maximum number of tickets were bought

NumberOfPassengersAtRoute( numberOfRoute )- returns the number           of passengers who went by given route

ManagerWithMaximumNumberOfSubordinates() - returns the managers         with maximum number of subordinates

StationsWhereMostOfTicketsWereBoughtFromMachines() - returns the         stations where the maximum number of tickets were bought from Machines

quitApp() - if you want to quit this application

In [12]:
NumberOfPassengersAtRoute(2)

20

Here you can find the set of requests available now

get( entity ) - shows the table of entity

RouteByNumber( numberOfRoute ) - returns the ordered set of           stations in given route

NumberOfTicketsAtStation( nameOfStation ) - returns the number           of tickets bought at given station

MaxStationByNumberOfTickets() - returns the stations, where the           maximum number of tickets were bought

NumberOfPassengersAtRoute( numberOfRoute )- returns the number           of passengers who went by given route

ManagerWithMaximumNumberOfSubordinates() - returns the managers         with maximum number of subordinates

StationsWhereMostOfTicketsWereBoughtFromMachines() - returns the         stations where the maximum number of tickets were bought from Machines

quitApp() - if you want to quit this application

In [13]:
ManagerWithMaximumNumberOfSubordinates()

Ковалева Надежда Эдуардовна

Here you can find the set of requests available now

get( entity ) - shows the table of entity

RouteByNumber( numberOfRoute ) - returns the ordered set of           stations in given route

NumberOfTicketsAtStation( nameOfStation ) - returns the number           of tickets bought at given station

MaxStationByNumberOfTickets() - returns the stations, where the           maximum number of tickets were bought

NumberOfPassengersAtRoute( numberOfRoute )- returns the number           of passengers who went by given route

ManagerWithMaximumNumberOfSubordinates() - returns the managers         with maximum number of subordinates

StationsWhereMostOfTicketsWereBoughtFromMachines() - returns the         stations where the maximum number of tickets were bought from Machines

quitApp() - if you want to quit this application

In [15]:
StationsWhereMostOfTicketsWereBoughtFromMachines()

Академическая
Александровский сад
Алексеевская
Алтуфьево
Аннино
Баррикадная
Библиотека имени Ленина
Бульвар адмирала Ушакова
Бульвар Дмитрия Донского
Бунинская аллея
Варшавская
ВДНХ
Владыкино
Водный стадион
Войковская
Воробьёвы горы
Выставочный центр
Деловой центр
Домодедовская
Каховская
Комсомольская
Красносельская
Красные ворота
Кропоткинская
Кузнецкий мост
Кузьминки
Курская
Кутузовская
Ленинский проспект
Медведково
Менделеевская
Нагорная
Новогиреево
Новокузнецкая
Новослободская
Октябрьское поле
Орехово
Партизанская
Перово
Петровско-Разумовская
Пионерская
Планерная
Полянка
Преображенская площадь
Пушкинская
Речной вокзал
Рижская
Римская
Рязанский проспект
Савёловская
Семёновская
Смоленская
Сокольники
Сретенский бульвар
Строгино
Сухаревская
Таганская
Тверская
Тульская
Тургеневская
Улица Академика Королёва
Улица Подбельского
Улица Сергея Эйзенштейна
Улица Скобелевская
Фили
Цветной бульвар
Чистые пруды
Ясенево

Here you can find the set of requests available now

get( entity ) - shows the table of entity

RouteByNumber( numberOfRoute ) - returns the ordered set of           stations in given route

NumberOfTicketsAtStation( nameOfStation ) - returns the number           of tickets bought at given station

MaxStationByNumberOfTickets() - returns the stations, where the           maximum number of tickets were bought

NumberOfPassengersAtRoute( numberOfRoute )- returns the number           of passengers who went by given route

ManagerWithMaximumNumberOfSubordinates() - returns the managers         with maximum number of subordinates

StationsWhereMostOfTicketsWereBoughtFromMachines() - returns the         stations where the maximum number of tickets were bought from Machines

quitApp() - if you want to quit this application